//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaSample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.HydrantLocations = new HashSet<HydrantLocation>();
        }
    
        public int city_Id { get; set; }
        public string city_Name { get; set; }
        public int city_State { get; set; }
        public Nullable<int> city_District { get; set; }
    
        public virtual ICollection<HydrantLocation> HydrantLocations { get; set; }
    }
}
