//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaSample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class District
    {
        public District()
        {
            this.HydrantLocations = new HashSet<HydrantLocation>();
        }
    
        public int district_Id { get; set; }
        public string district_Name { get; set; }
    
        public virtual ICollection<HydrantLocation> HydrantLocations { get; set; }
    }
}
