//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaSample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HydrantInfo
    {
        public int hydrant_Id { get; set; }
        public int Test { get; set; }
        public int Function { get; set; }
        public string Video { get; set; }
        public string Photo { get; set; }
        public int Replacement { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Comments { get; set; }
    }
}
