//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaSample.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HydrantConnectionEntities : DbContext
    {
        public HydrantConnectionEntities()
            : base("name=HydrantConnectionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<City> Cities { get; set; }
        public DbSet<District> Districts { get; set; }
        public DbSet<HydrantInfo> HydrantInfoes { get; set; }
        public DbSet<HydrantLocation> HydrantLocations { get; set; }
        public DbSet<Test_Hydrant> Test_Hydrant { get; set; }
    }
}
